# Generated by Django 3.0.5 on 2020-04-19 18:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200415_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
