# Generated by Django 3.0.5 on 2020-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200419_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
