# Generated by Django 3.0.5 on 2020-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200501_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='slider1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='slider2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='slider3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
