# Generated by Django 3.0.5 on 2020-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kimliknum',
            field=models.IntegerField(blank=True),
        ),
    ]
