# Generated by Django 3.0.5 on 2020-06-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200511_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kimliknum',
        ),
    ]
